"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { useSession } from "@/lib/session";

const base = process.env.NEXT_PUBLIC_ADMIN_API_BASE ?? "http://localhost:8000";
type Suggestion = { id: string; kind: string; evidence: Record<string, unknown>; proposed_rule: Record<string, unknown>; status: string };
const labels: Record<string, string> = { unpoliced_detection: "Unpoliced detection", recurring_unknown_pattern: "Recurring unknown pattern", overblocking_warning: "Over-blocking warning", context_loss_warning: "Context-loss warning" };
async function admin<T>(token: string, path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${base}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" } }); if (!response.ok) throw new Error(response.status === 403 ? "Your role does not allow this action." : "Could not update the suggestion."); return response.json() as Promise<T>; }
export default function SuggestionsPage() { const { session } = useSession(); const mayWrite = session.role === "owner" || session.role === "admin"; const [items, setItems] = useState<Suggestion[]>([]); const [error, setError] = useState(""); const load = () => admin<{ items: Suggestion[] }>(session.token, "/admin/suggestions").then((result) => setItems(result.items)).catch((item: unknown) => setError(item instanceof Error ? item.message : "Could not load suggestions.")); useEffect(() => { void load(); }, [session.token]); const resolve = async (item: Suggestion, action: "apply" | "dismiss") => { setError(""); try { await admin(session.token, `/admin/suggestions/${item.id}/${action}`, { method: "POST" }); setItems((current) => current.filter((entry) => entry.id !== item.id)); } catch (failure) { setError(failure instanceof Error ? failure.message : "Could not update suggestion."); } }; return <AppShell><div className="mx-auto max-w-4xl"><header><h1 className="text-2xl font-semibold">Suggestions</h1><p className="mt-1 text-sm text-muted">Recommendations use aggregate audit evidence. They never show matched prompt values.</p></header>{error && <p role="alert" className="mt-5 rounded border border-blocked p-3 text-sm">{error}</p>}<div className="mt-6 space-y-4">{items.length === 0 ? <div className="rounded border border-hairline p-6 text-sm text-muted">No open suggestions. Continue reviewing false-positive reports and policy outcomes.</div> : items.map((item) => <article key={item.id} className="rounded border border-hairline p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted">{labels[item.kind] ?? item.kind}</p><h2 className="mt-1 text-lg font-semibold">Review this configuration recommendation</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted">Evidence</dt><dd className="mt-1 rounded bg-raised p-2 font-mono text-xs">{JSON.stringify(item.evidence)}</dd></div><div><dt className="text-muted">Proposed change</dt><dd className="mt-1 rounded bg-raised p-2 font-mono text-xs">{JSON.stringify(item.proposed_rule)}</dd></div></dl><div className="mt-4 flex gap-3"><button className="rounded border border-hairline px-3 py-2 text-sm disabled:opacity-50" disabled={!mayWrite} onClick={() => void resolve(item, "apply")}>Apply recommendation</button><button className="rounded border border-hairline px-3 py-2 text-sm disabled:opacity-50" disabled={!mayWrite} onClick={() => void resolve(item, "dismiss")}>Dismiss</button></div></article>)}</div></div></AppShell>; }
